/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MATHSPEC_H_RPCGEN
#define _MATHSPEC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operations {
	int op1;
	int op2;
	int arr[20];
	int len;
	int result;
	int operation;
};
typedef struct operations operations;

#define MATHPROG 0x21111111
#define INITIAL 1

#if defined(__STDC__) || defined(__cplusplus)
#define MATHPROC 1
extern  operations * mathproc_1(operations *, CLIENT *);
extern  operations * mathproc_1_svc(operations *, struct svc_req *);
extern int mathprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MATHPROC 1
extern  operations * mathproc_1();
extern  operations * mathproc_1_svc();
extern int mathprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operations (XDR *, operations*);

#else /* K&R C */
extern bool_t xdr_operations ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MATHSPEC_H_RPCGEN */
