/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "MathSpec.h"

operations *
mathproc_1_svc(operations *argp, struct svc_req *rqstp)
{
	static operations  result;

	/*
	 * insert server code here
	 */

	return &result;
}
