/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "MathSpec.h"


void
mathprog_1(char *host)
{
	CLIENT *clnt;
	operations  *result_1;
	operations  mathproc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MATHPROG, INITIAL, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = mathproc_1(&mathproc_1_arg, clnt);
	if (result_1 == (operations *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	mathprog_1 (host);
exit (0);
}
