/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "digsum.h"
#include <stdio.h>

out *
addproc_1_svc(in *inp, struct svc_req *rqstp)
{
	static out output;
	
	long int n1=inp->num1;
	long int n2=inp->num2;
	long int sm1=0;
	long int sm2=0;
	while(n1)
	{
		sm1+=n1%10;
		n1/=10;
	}
	while(n2)
	{
		sm2+=n2%10;
		n2/=10;
	}
	output.res=sm1+sm2;
	return (&output);
}
