/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "digsum.h"


void
add_prog_1(char *host)
{
	CLIENT *clnt;
	out  *result_1;
	in  addproc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter the number\n");
	scanf("%ld %ld",&addproc_1_arg.num1,&addproc_1_arg.num2);

	result_1 = addproc_1(&addproc_1_arg, clnt);
	if (result_1 == (out *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
		printf("The digit sum value is %ld\n",result_1->res);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host);
exit (0);
}
