/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "digsum.h"

bool_t
xdr_in (XDR *xdrs, in *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_long (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_out (XDR *xdrs, out *objp)
{
	register int32_t *buf;

	 if (!xdr_long (xdrs, &objp->res))
		 return FALSE;
	return TRUE;
}
